/*##############################################################################################
#                                                                                              #
#     #############       #############       #############       ####                ####     #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #     #    #########      #    #####    #     #    #              #    #    #
#    #    #   #    #     #    #              #    #   #    #     #    #              #    #    #
#    #    #####    #     #    #              #    #####    #     #    #              #    #    #
#    #             #     #    #########      #             #     #    #              #    #    #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #      #########    #     #    #####    #     #    #              #    #    #
#    #    #   #    #              #    #     #    #   #    #     #    #              #    #    #
#    #    #   #    #      #########    #     #    #   #    #     #    #########      #    #    #
#    #    #   #    #     #             #     #    #   #    #     #             #     #    #    #
#     ####     ####       #############       ####     ####       #############       ####     #
#                                                                                              #
#   Department of Energy                                                                       #
#   Politecnico di Milano                                                                      #
#   Author: Stefano Rebughini <stefano.rebughini@polimi.it>                                    #
#                                                                                              #
################################################################################################
#                                                                                              #
#   License                                                                                    #
#                                                                                              #
#   This file is part of ASALI.                                                                #
#                                                                                              #
#   ASALI is free software: you can redistribute it and/or modify                              #
#   it under the terms of the GNU General Public License as published by                       #
#   the Free Software Foundation, either version 3 of the License, or                          #
#   (at your option) any later version.                                                        #
#                                                                                              #
#   ASALI is distributed in the hope that it will be useful,                                   #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of                             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                              #
#   GNU General Public License for more details.                                               #
#                                                                                              #
#   You should have received a copy of the GNU General Public License                          #
#   along with ASALI. If not, see <http://www.gnu.org/licenses/>.                              #
#                                                                                              #
##############################################################################################*/
unsigned int              Ntot;
unsigned int              Nx;
unsigned int              Ny;
unsigned int              Nz;

std::vector<double>       xMesh;
std::vector<double>       yMesh;
std::vector<double>       zMesh;

std::vector<std::string>  bMeshName;
std::vector<unsigned int> bMeshIndex;

ASALI::readMesh           meshFile;
{
    //- Read mesh file
    {
        meshFile.read();
    }
    
    //- Get points
    {
        Nx    = meshFile.getXnumberOfPoints();
        Ny    = meshFile.getYnumberOfPoints();
        Nz    = meshFile.getZnumberOfPoints();
        Ntot  = Nx*Ny*Nz;

        xMesh = meshFile.getXpoints();
        yMesh = meshFile.getYpoints();
        zMesh = meshFile.getZpoints();
    }

    //- Get boundaries
    {
        bMeshName  = meshFile.getBoundariesName();
        bMeshIndex = meshFile.getBoundariesIndex();
    }
}
